### PR TITLE
Update test.yml

### PR DESCRIPTION
**Pull request by benlei-gfm**

### CODE REVIEW

**Comment by benlei-gfm** [comment]
bors merge

**Comment by ehannah-gfm** [comment]
bors merge

**Comment by ehannah-gfm** [comment]
bors cancel

**Comment by benlei-gfm** [comment]
bors merge

**Comment by benlei-gfm** [comment]
bleh, whatever - you can probably test it but I was trying to see if a "pull_request" action gets run if bors merged.

if it didn't, then that means we wouldn't want a "pull_request" section.

**Comment by ehannah-gfm** [comment]
@benlei-gfm so the pull request action does run if its triggered by a bors merge.

https://user-images.githubusercontent.com/91637793/180286229-705801dd-f5fe-41a6-8ddc-4a4edb613ae1.mov

**Comment by benlei-gfm** [comment]
That looks like it triggered because the PR was opened, and that it says "Merged by Bors" because the PR was renamed post-Bors merge. Note that in partner team's github actions, they've set the on.pull_request to only happen with certain actions, NOT all.

**Pull request closed without merging**
